/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AutomobileWorkArea;

import Business.BudgetData.Budget;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Events.Event;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author saurabhkulkarni
 */
public class AutomobileAdminJpanel extends javax.swing.JPanel {

    /**
     * Creates new form AutomobileAdminJpanel
     */
     private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    private ArrayList<Budget> tempBudgetList;
    private ArrayList<Event> tempAutoEventList;
    int i =1;
    
    public AutomobileAdminJpanel(JPanel userProcessContainer, Enterprise enterprise,UserAccount userAccount, EcoSystem business) {
        initComponents();
        this.userProcessContainer =userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;
        tempBudgetList = new ArrayList<Budget>();
        tempAutoEventList = new ArrayList<Event>();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAutoBudget = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("ALLOCATED BUDGET TO THIS ORG FOR THIS YEAR");

        btnAutoBudget.setBackground(new java.awt.Color(255, 255, 255));
        btnAutoBudget.setText("View Current Budget");
        btnAutoBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoBudgetActionPerformed(evt);
            }
        });

        jButton1.setText("View graphically");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(189, 189, 189))
            .addGroup(layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAutoBudget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnAutoBudget)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(407, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAutoBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoBudgetActionPerformed
        // TODO add your handling code here:
        ViewAutomobileBudgetJPanel viewAutomobileBudgetJPanel = new ViewAutomobileBudgetJPanel(userProcessContainer, enterprise, userAccount,business);
        userProcessContainer.add("viewAutomobileBudgetJPanel", viewAutomobileBudgetJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAutoBudgetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:for(Network net: business.getNetworkList()){
           for(Network net: business.getNetworkList()){
            for(Enterprise ent: net.getEnterpriseDirectory().getEnterpriseList()){
                if(ent.getEnterpriseType() == Enterprise.EnterpriseType.GoGreenEnterprise){
                    for(WorkRequest request: ent.getWorkQueue().getWorkRequestlist()){
                        for(Budget budget: request.getBudgetList()){
                            tempBudgetList.add(budget); 
                            for(Event event : budget.getEventList())
                            {
                                if(event.getOrganisationOfEvent().equals("Automobile"))
                                {
                                    tempAutoEventList.add(event);
                                }
                            }
                            }
                        }
                    }
                }
            }
        
        System.out.println("tempBudgetList: "+tempBudgetList.size());
        int budgetAuto =0;
        for(Budget budget : tempBudgetList)
        {
            if(budget.getOrgName().equals("Automobile"))
            {
                budgetAuto= budget.getOrgBudget();
                
            }
        }
        
       
        
        
        
        
        System.out.println("budget for Automobile org " +budgetAuto);
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        String series1 = "Current year budget";
        String series2 = "Event1";
        String series3 = "Event2";
        String series4 = "Event3";
        
        
        dataset.addValue(budgetAuto, series1,"Total Automobile Budget");
        
        for(Event e : tempAutoEventList)
        {
            dataset.addValue(e.getEventBudget(),("series"+i),e.getEventName());
            i++;
        }
        
        
        
//        dataset.addValue(, series2,"Laugh");
//        dataset.addValue(5,series3, "Marathon");
//        dataset.addValue(12, series4,"Health camps");
        
        
        JFreeChart jchart = ChartFactory.createBarChart("Curren year budget split", "Org and events", "Budget", dataset, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel myChart = new ChartPanel(jchart);
        
        
        CategoryPlot plot = jchart.getCategoryPlot();
        plot.getRenderer().setSeriesPaint(1,Color.ORANGE);
        plot.getRenderer().setSeriesPaint(2,Color.BLACK);
        plot.getRenderer().setSeriesPaint(3,Color.DARK_GRAY);
        
        plot.getRenderer().setSeriesPaint(4,Color.GREEN);
        
        
        
        ChartFrame chartfrm = new ChartFrame("Budget Record", jchart,true);
        
        chartfrm.setSize(1700,800);
        chartfrm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutoBudget;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
