/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.IndustriesWorkArea;

import Business.BudgetData.Budget;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Events.Event;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author saurabhkulkarni
 */
public class IndustriesAdminJpanel extends javax.swing.JPanel {

    /**
     * Creates new form IndustriesAdminJpanel
     */
     private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
     private ArrayList<Budget> tempBudgetList;
    private ArrayList<Event> tempIndEventList;
    int i =1;
    
    public IndustriesAdminJpanel(JPanel userProcessContainer, Enterprise enterprise,UserAccount userAccount,EcoSystem business) {
        initComponents();
                this.userProcessContainer =userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;
         tempBudgetList = new ArrayList<Budget>();
        tempIndEventList = new ArrayList<Event>();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCurrentBudget1 = new javax.swing.JButton();
        IndustriesGraphBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("ALLOCATED BUDGET TO THIS ORG FOR THIS YEAR");

        btnCurrentBudget1.setText("View Current Budget");
        btnCurrentBudget1.setToolTipText("");
        btnCurrentBudget1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurrentBudget1ActionPerformed(evt);
            }
        });

        IndustriesGraphBtn.setText("View graphically");
        IndustriesGraphBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndustriesGraphBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCurrentBudget1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(IndustriesGraphBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(224, 224, 224))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnCurrentBudget1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IndustriesGraphBtn)
                .addContainerGap(404, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCurrentBudget1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurrentBudget1ActionPerformed
        // TODO add your handling code here:
        ViewIndustriesBudgetJPanel viewIndustriesBudgetJPanel = new ViewIndustriesBudgetJPanel(userProcessContainer, enterprise, userAccount,business);
        userProcessContainer.add("viewIndustriesBudgetJPanel", viewIndustriesBudgetJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCurrentBudget1ActionPerformed

    private void IndustriesGraphBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndustriesGraphBtnActionPerformed
        // TODO add your handling code here:
     for(Network net: business.getNetworkList()){
            for(Enterprise ent: net.getEnterpriseDirectory().getEnterpriseList()){
                if(ent.getEnterpriseType() == Enterprise.EnterpriseType.GoGreenEnterprise){
                    for(WorkRequest request: ent.getWorkQueue().getWorkRequestlist()){
                        for(Budget budget: request.getBudgetList()){
                            tempBudgetList.add(budget); 
                            for(Event event : budget.getEventList())
                            {
                                if(event.getOrganisationOfEvent().equals("Industries"))
                                {
                                    tempIndEventList.add(event);
                                }
                            }
                            }
                        }
                    }
                }
            }
        
        System.out.println("tempBudgetList: "+tempBudgetList.size());
        int budgetInd =0;
        for(Budget budget : tempBudgetList)
        {
            if(budget.getOrgName().equals("Industries"))
            {
                budgetInd= budget.getOrgBudget();
                
            }
        }
        
       
        
        
        
        
        System.out.println("budget for Automobile org " +budgetInd);
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        String series1 = "Current year budget";
        String series2 = "Event1";
        String series3 = "Event2";
        String series4 = "Event3";
        
        
        dataset.addValue(budgetInd, series1,"Total Industries Budget");
        
        for(Event e : tempIndEventList)
        {
            dataset.addValue(e.getEventBudget(),("series"+i),e.getEventName());
            i++;
        }
        
        
        
//        dataset.addValue(, series2,"Laugh");
//        dataset.addValue(5,series3, "Marathon");
//        dataset.addValue(12, series4,"Health camps");
        
        
        JFreeChart jchart = ChartFactory.createBarChart("Curren year budget split", "Org and events", "Budget", dataset, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel myChart = new ChartPanel(jchart);
        
        
        CategoryPlot plot = jchart.getCategoryPlot();
        plot.getRenderer().setSeriesPaint(1,Color.ORANGE);
        plot.getRenderer().setSeriesPaint(2,Color.BLACK);
        plot.getRenderer().setSeriesPaint(3,Color.DARK_GRAY);
        
        plot.getRenderer().setSeriesPaint(4,Color.GREEN);
        
        
        
        ChartFrame chartfrm = new ChartFrame("Budget Record", jchart,true);
        
        chartfrm.setSize(1700,800);
        chartfrm.setVisible(true);
    }//GEN-LAST:event_IndustriesGraphBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IndustriesGraphBtn;
    private javax.swing.JButton btnCurrentBudget1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
