/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EducationWorkArea;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author saurabhkulkarni
 */
public class EducationAdminJpanel extends javax.swing.JPanel {

    /**
     * Creates new form EducationAdminJpanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;

    public EducationAdminJpanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCurrentBudget = new javax.swing.JButton();
        btnEduEvents = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("ALLOCATED BUDGET TO THIS ORG FOR THIS YEAR");

        btnCurrentBudget.setBackground(new java.awt.Color(255, 255, 255));
        btnCurrentBudget.setText("View Current Budget");
        btnCurrentBudget.setToolTipText("");
        btnCurrentBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurrentBudgetActionPerformed(evt);
            }
        });

        btnEduEvents.setText("Events At a Glance");
        btnEduEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEduEventsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCurrentBudget, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(btnEduEvents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(275, 275, 275))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(btnCurrentBudget)
                .addGap(34, 34, 34)
                .addComponent(btnEduEvents)
                .addContainerGap(354, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCurrentBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurrentBudgetActionPerformed
        // TODO add your handling code here:
        ViewEducationBudgetJPanel viewEducationBudgetJPanel = new ViewEducationBudgetJPanel(userProcessContainer, enterprise, userAccount);
        userProcessContainer.add("viewEducationBudgetJPanel", viewEducationBudgetJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCurrentBudgetActionPerformed

    private void btnEduEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEduEventsActionPerformed
        // TODO add your handling code here:
        EducationEventsJPanel educationEventsJPanel = new EducationEventsJPanel(userProcessContainer, enterprise, userAccount);
        userProcessContainer.add("educationEventsJPanel", educationEventsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnEduEventsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCurrentBudget;
    private javax.swing.JButton btnEduEvents;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
