/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.InfrastructureWorkArea;

import Business.BudgetData.Budget;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Events.Event;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author saurabhkulkarni
 */
public class InfrastructureAdminJpanel extends javax.swing.JPanel {

    /**
     * Creates new form BuildingsAdminJpanel
     */
     private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
     private ArrayList<Budget> tempBudgetList;
    private ArrayList<Event> tempInfraEventList;
    int i =1;
    public InfrastructureAdminJpanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount userAccount, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business =business;
         tempBudgetList = new ArrayList<Budget>();
        tempInfraEventList = new ArrayList<Event>();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCurrentBudget = new javax.swing.JButton();
        InfraViewGraphicallyBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("ALLOCATED BUDGET TO THIS ORG FOR THIS YEAR");

        btnCurrentBudget.setBackground(new java.awt.Color(255, 255, 255));
        btnCurrentBudget.setText("View Current Budget");
        btnCurrentBudget.setToolTipText("");
        btnCurrentBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurrentBudgetActionPerformed(evt);
            }
        });

        InfraViewGraphicallyBtn.setBackground(new java.awt.Color(255, 255, 255));
        InfraViewGraphicallyBtn.setText("View graphically");
        InfraViewGraphicallyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfraViewGraphicallyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(189, 189, 189))
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InfraViewGraphicallyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCurrentBudget, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(btnCurrentBudget)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InfraViewGraphicallyBtn)
                .addContainerGap(366, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCurrentBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurrentBudgetActionPerformed
        // TODO add your handling code here:
        ViewInfrastructureBudgetJPanel viewInfrastructureBudgetJPanel = new ViewInfrastructureBudgetJPanel(userProcessContainer, enterprise, userAccount,business);
        userProcessContainer.add("viewInfrastructureBudgetJPanel", viewInfrastructureBudgetJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCurrentBudgetActionPerformed

    private void InfraViewGraphicallyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfraViewGraphicallyBtnActionPerformed
        // TODO add your handling code here:
        
        for(Network net: business.getNetworkList()){
            for(Enterprise ent: net.getEnterpriseDirectory().getEnterpriseList()){
                if(ent.getEnterpriseType() == Enterprise.EnterpriseType.GoGreenEnterprise){
                    for(WorkRequest request: ent.getWorkQueue().getWorkRequestlist()){
                        for(Budget budget: request.getBudgetList()){
                            tempBudgetList.add(budget); 
                            for(Event event : budget.getEventList())
                            {
                                if(event.getOrganisationOfEvent().equals("Infrastructure"))
                                {
                                    tempInfraEventList.add(event);
                                }
                            }
                            }
                        }
                    }
                }
            }
        
        System.out.println("tempBudgetList: "+tempBudgetList.size());
        int budgetInfra =0;
        for(Budget budget : tempBudgetList)
        {
            if(budget.getOrgName().equals("Infrastructure"))
            {
                budgetInfra= budget.getOrgBudget();
                
            }
        }
        
       
        
        
        
        
        System.out.println("budget for  org " +budgetInfra);
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        String series1 = "Current year budget";
        String series2 = "Event1";
        String series3 = "Event2";
        String series4 = "Event3";
        
        
        dataset.addValue(budgetInfra, series1,"Total Infrastructure Budget");
        
        for(Event e : tempInfraEventList)
        {
            dataset.addValue(e.getEventBudget(),("series"+i),e.getEventName());
            i++;
        }
        
        
        
//        dataset.addValue(, series2,"Laugh");
//        dataset.addValue(5,series3, "Marathon");
//        dataset.addValue(12, series4,"Health camps");
        
        
        JFreeChart jchart = ChartFactory.createBarChart("Curren year budget split", "Org and events", "Budget", dataset, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel myChart = new ChartPanel(jchart);
        
        
        CategoryPlot plot = jchart.getCategoryPlot();
        plot.getRenderer().setSeriesPaint(1,Color.ORANGE);
        plot.getRenderer().setSeriesPaint(2,Color.BLACK);
        plot.getRenderer().setSeriesPaint(3,Color.DARK_GRAY);
        
        plot.getRenderer().setSeriesPaint(4,Color.GREEN);
        
        
        
        ChartFrame chartfrm = new ChartFrame("Budget Record", jchart,true);
        
        chartfrm.setSize(1700,800);
        chartfrm.setVisible(true);
    }//GEN-LAST:event_InfraViewGraphicallyBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InfraViewGraphicallyBtn;
    private javax.swing.JButton btnCurrentBudget;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
