/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminArea;

import Business.BudgetData.Budget;
import Business.EcoSystem;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author saurabhkulkarni
 */
public class DisplayPastUtilizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayPastUtilizationJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;

    public DisplayPastUtilizationJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        show = new javax.swing.JButton();
        backJButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        show.setBackground(new java.awt.Color(255, 255, 255));
        show.setText("Display Department Budget");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        backJButton2.setBackground(new java.awt.Color(255, 255, 255));
        backJButton2.setText("Back");
        backJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backJButton2)
                    .addComponent(show))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(show)
                .addGap(30, 30, 30)
                .addComponent(backJButton2)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
       //chartpanel.removeAll();
       DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        String series1 = "2011 Allocated";
        String series2 = "2011 Used";
        
        String series3 = "2012 Allocated";
        String series4 = "2012 Used";
        
        String series5= "2013 Allocated";
        String series6 = "2013 Used";
        
        String series7= "2014 Allocated";
        String series8 = "2014 Used";
   
        
        //        cdc.setValue(60.90,"Marks","Ganesh");
        //        cdc.setValue(70.90,"Marks","Suresh");
        //        cdc.setValue(80.90,"Marks","Ramesh");
        //        cdc.setValue(100.90,"Marks","Kamlesh");

        for (Budget budget : system.getCsvUtil().getPreviousBudgetlist()) {
            if(budget.getBudgetYear() == 2011)
            {
                dataset.addValue(budget.getOrgBudget(), series1,budget.getOrgName());
                dataset.addValue(budget.getBudgetUsed(), series2,budget.getOrgName());
                
            }
           
            if(budget.getBudgetYear() == 2012)
            {
                dataset.addValue(budget.getOrgBudget(), series3, budget.getOrgName());
                dataset.addValue(budget.getBudgetUsed(), series4, budget.getOrgName());
            }
            
            
            if(budget.getBudgetYear()== 2013)
            {
                dataset.addValue(budget.getOrgBudget(), series5, budget.getOrgName());
                dataset.addValue(budget.getBudgetUsed(), series6, budget.getOrgName());
            }
            
             if(budget.getBudgetYear()== 2014)
            {
                dataset.addValue(budget.getOrgBudget(), series7, budget.getOrgName());
                dataset.addValue(budget.getBudgetUsed(), series8, budget.getOrgName());
            }
//           
        }

        JFreeChart jchart = ChartFactory.createBarChart("Budget Record", "Organization Name", "Orgzanition Budget", dataset, PlotOrientation.VERTICAL, true, true, false);
        
        //CategoryPlot plot = jchart.getCategoryPlot();
        //ChartPanel chartPanel = new ChartPanel(jchart);
        ChartPanel myChart = new ChartPanel(jchart);
        
//        jPanel2.add(myChart);
//        jPanel2.validate();
//        jPanel2.repaint();
//        userProcessContainer.add(myChart);
//        userProcessContainer.validate();
//        userProcessContainer.repaint();
//        JPanel.add(myChart);
//        JPanel.validate();
//        JPanel.repaint();
        
        
       
       // plot.setRangeGridlinePaint(Color.BLACK);
        CategoryPlot plot = jchart.getCategoryPlot();
        plot.getRenderer().setSeriesPaint(0, Color.BLUE);
        plot.getRenderer().setSeriesPaint(1,Color.ORANGE);
        plot.getRenderer().setSeriesPaint(2,Color.BLACK);
        plot.getRenderer().setSeriesPaint(3,Color.DARK_GRAY);
        plot.getRenderer().setSeriesPaint(4,Color.GREEN);
        plot.getRenderer().setSeriesPaint(5,Color.MAGENTA);
        plot.getRenderer().setSeriesPaint(6,Color.PINK);
        plot.getRenderer().setSeriesPaint(7,Color.RED);
        plot.getRenderer().setSeriesPaint(8,Color.WHITE);
        ChartFrame chartfrm = new ChartFrame("Budget Record", jchart,true);
        
        chartfrm.setSize(1700,800);
        chartfrm.setVisible(true);


 
    }//GEN-LAST:event_showActionPerformed

    
    
    
    private void backJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton2ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton show;
    // End of variables declaration//GEN-END:variables
}
