/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminArea;

import Business.BudgetData.Budget;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Events.Event;
import Business.Network.Network;
import Business.WorkRequest.WorkRequest;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author amaha
 */
public class FinalBudgetAllocationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FinalBudgetAllocationJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private ArrayList<Budget> tempList;
    int i =1;
   

    FinalBudgetAllocationJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = system;
        tempList= new ArrayList<Budget>();
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("View graphically");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jButton1)
                .addContainerGap(251, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addContainerGap(418, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        for(Network net: business.getNetworkList()){
            for(Enterprise ent: net.getEnterpriseDirectory().getEnterpriseList()){
                if(ent.getEnterpriseType() == Enterprise.EnterpriseType.GoGreenEnterprise){
                    for(WorkRequest request: ent.getWorkQueue().getWorkRequestlist()){
                        for(Budget budget: request.getBudgetList())
                        {
                            tempList.add(budget);
                        }
                }
            }
        }
    }
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        for(Budget budget : tempList)
        {
            dataset.addValue(budget.getOrgBudget(),("series"+i),budget.getOrgName());
            i++;
        }
        
        JFreeChart jchart = ChartFactory.createBarChart("Curren year budget split", "Org and events", "Budget", dataset, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel myChart = new ChartPanel(jchart);
        
        
        CategoryPlot plot = jchart.getCategoryPlot();
        plot.getRenderer().setSeriesPaint(1,Color.ORANGE);
        plot.getRenderer().setSeriesPaint(2,Color.BLACK);
        plot.getRenderer().setSeriesPaint(3,Color.DARK_GRAY);
        
        plot.getRenderer().setSeriesPaint(4,Color.GREEN);
        
        
        
        ChartFrame chartfrm = new ChartFrame("Budget Record", jchart,true);
        
        chartfrm.setSize(1700,800);
        chartfrm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
