/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminArea;

import Business.BudgetData.BudgetDirectory;
import Business.EcoSystem;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author amaha
 */
public class SendOrganizationBudgetJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    private BudgetDirectory budgetDirectory;
    private WorkRequest workRequest;

    /**
     * Creates new form SendOrganizationBudgetJPanel
     */
  //  public SendOrganizationBudgetJPanel(JPanel userProcessContainer, EcoSystem business, UserAccount userAccount) {
    SendOrganizationBudgetJPanel(JPanel userProcessContainer, EcoSystem system, UserAccount userAccount) {
        initComponents();
        workRequest = new WorkRequest();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = system;
       // this.budgetDirectory = budgetDirectory;
    }

    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHCBudget = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnHCSend = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        educationTxtfield = new javax.swing.JTextField();
        EducationSendBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        txtHCBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHCBudgetActionPerformed(evt);
            }
        });

        jLabel1.setText("Health Care Department : ");

        btnHCSend.setBackground(new java.awt.Color(255, 255, 255));
        btnHCSend.setText("Send");
        btnHCSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHCSendActionPerformed(evt);
            }
        });

        jLabel2.setText("Education Department : ");

        EducationSendBtn.setBackground(new java.awt.Color(255, 255, 255));
        EducationSendBtn.setText("Send");
        EducationSendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EducationSendBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHCBudget, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(educationTxtfield))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHCSend)
                    .addComponent(EducationSendBtn))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHCBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnHCSend))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(educationTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EducationSendBtn))
                .addContainerGap(187, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtHCBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHCBudgetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHCBudgetActionPerformed

    private void btnHCSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHCSendActionPerformed
        //TODO add your handling code here:
        workRequest.setMessage(txtHCBudget.getText());
        workRequest.setSender(userAccount);
        workRequest.setStatus("Sent");
        //workRequest.setBudgetList(budgetDirectory.getBudgetList());
        workRequest.setReceiver(Role.RoleType.HealthCareAdmin);
        UserAccount user = null;
        System.out.println("Net list : " + business.getNetworkList().size());
       for(Network network : business.getNetworkList())
       {
           for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList())
           {
               for(Organization org : enterprise.getOrganisationDirectory().getOrganisationList())
               {
                   for(UserAccount userAccount : org.getUserAccDir().getUserAccountList())
                   {
                       if(userAccount.getUsername().equals("ok"))
                       {
                           user = userAccount;
                       }
                   }
               }
           }
       }
        if (user != null) {
            user.getWorkQueue().getWorkRequestlist().add(workRequest);
            JOptionPane.showMessageDialog(null, "Budget send for HealthCare Department", "Information", JOptionPane.INFORMATION_MESSAGE);

            System.out.println("req:" + user.getWorkQueue().getWorkRequestlist().size());
            System.out.println("req:" + user.getWorkQueue().getWorkRequestlist().get(0).getMessage().toString());
            System.out.println("req:" + user.getWorkQueue().getWorkRequestlist().get(0).getSender().toString());
        }
        
//         Organization org = null;
//        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
//            if (organization instanceof LabOrganization){
//                org = organization;
//                break;
//            }
//        }
//        if (org!=null){
//            org.getWorkQueue().getWorkRequestList().add(request);
//            userAccount.getWorkQueue().getWorkRequestList().add(request);
//        }
    }//GEN-LAST:event_btnHCSendActionPerformed

    private void EducationSendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EducationSendBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EducationSendBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EducationSendBtn;
    private javax.swing.JButton btnHCSend;
    private javax.swing.JTextField educationTxtfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtHCBudget;
    // End of variables declaration//GEN-END:variables
}
