/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HealthcareWorkArea;

import Business.BudgetData.Budget;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Events.Event;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.WorkRequest;
import UserInterface.BudgetAdminWorkArea.ManageUserAccountJPanel;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author saurabhkulkarni
 */
public class HealthcareAdminJpanel extends javax.swing.JPanel {

    /**
     * Creates new form HealthcareAdminJpanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private EcoSystem business;
    private UserAccount userAccount;
    private ArrayList<Budget> tempBudgetList;
    private ArrayList<Event> tempHealthEventList;
    int i =1;
  public HealthcareAdminJpanel(JPanel userProcessContainer, Enterprise enterprise,UserAccount userAccount, EcoSystem business) {
        initComponents();
        this.userProcessContainer =userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business=business;
        tempBudgetList = new ArrayList<Budget>();
        tempHealthEventList = new ArrayList<Event>();
    }

  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnViewHCEvents = new javax.swing.JButton();
        HealthViewGraphicallyBtn = new javax.swing.JButton();
        btnViewHCBudget1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("ALLOCATED BUDGET TO THIS ORG FOR THIS YEAR");

        btnViewHCEvents.setBackground(new java.awt.Color(255, 255, 255));
        btnViewHCEvents.setText("Events/Sessions at A Glance");
        btnViewHCEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHCEventsActionPerformed(evt);
            }
        });

        HealthViewGraphicallyBtn.setBackground(new java.awt.Color(255, 255, 255));
        HealthViewGraphicallyBtn.setText("View graphically");
        HealthViewGraphicallyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HealthViewGraphicallyBtnActionPerformed(evt);
            }
        });

        btnViewHCBudget1.setBackground(new java.awt.Color(255, 255, 255));
        btnViewHCBudget1.setText("View Budget");
        btnViewHCBudget1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHCBudget1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(223, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(189, 189, 189))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(HealthViewGraphicallyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewHCEvents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(311, 311, 311)
                    .addComponent(btnViewHCBudget1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addGap(277, 277, 277)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addComponent(HealthViewGraphicallyBtn)
                .addGap(31, 31, 31)
                .addComponent(btnViewHCEvents)
                .addContainerGap(329, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(btnViewHCBudget1)
                    .addContainerGap(424, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewHCEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHCEventsActionPerformed
        HealthCareEvents healthCareEvents = new HealthCareEvents(userProcessContainer, enterprise, userAccount);
        userProcessContainer.add("healthCareEvents", healthCareEvents);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnViewHCEventsActionPerformed

    private void HealthViewGraphicallyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HealthViewGraphicallyBtnActionPerformed
        // TODO add your handling code here:
        
         for(Network net: business.getNetworkList()){
            for(Enterprise ent: net.getEnterpriseDirectory().getEnterpriseList()){
                if(ent.getEnterpriseType() == Enterprise.EnterpriseType.GoGreenEnterprise){
                    for(WorkRequest request: ent.getWorkQueue().getWorkRequestlist()){
                        for(Budget budget: request.getBudgetList()){
                            tempBudgetList.add(budget); 
                            for(Event event : budget.getEventList())
                            {
                                if(event.getOrganisationOfEvent().equals("HealthCare"))
                                {
                                    tempHealthEventList.add(event);
                                }
                            }
                            }
                        }
                    }
                }
            }
        
        System.out.println("tempBudgetList: "+tempBudgetList.size());
        int budgetHealth =0;
        for(Budget budget : tempBudgetList)
        {
            if(budget.getOrgName().equals("HealthCare"))
            {
                budgetHealth= budget.getOrgBudget();
                
            }
        }
        
       
        
        
        
        
        System.out.println("budget for health org " +budgetHealth);
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        String series1 = "Current year budget";
        String series2 = "Event1";
        String series3 = "Event2";
        String series4 = "Event3";
        
        
        dataset.addValue(budgetHealth, series1,"Total health Budget");
        
        for(Event e : tempHealthEventList)
        {
            dataset.addValue(e.getEventBudget(),("series"+i),e.getEventName());
            i++;
        }
        
        
        
//        dataset.addValue(, series2,"Laugh");
//        dataset.addValue(5,series3, "Marathon");
//        dataset.addValue(12, series4,"Health camps");
        
        
        JFreeChart jchart = ChartFactory.createBarChart("Curren year budget split", "Org and events", "Budget", dataset, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel myChart = new ChartPanel(jchart);
        
        
        CategoryPlot plot = jchart.getCategoryPlot();
        plot.getRenderer().setSeriesPaint(1,Color.ORANGE);
        plot.getRenderer().setSeriesPaint(2,Color.BLACK);
        plot.getRenderer().setSeriesPaint(3,Color.DARK_GRAY);
        
        plot.getRenderer().setSeriesPaint(4,Color.GREEN);
        
        
        
        ChartFrame chartfrm = new ChartFrame("Budget Record", jchart,true);
        
        chartfrm.setSize(1700,800);
        chartfrm.setVisible(true);
    }//GEN-LAST:event_HealthViewGraphicallyBtnActionPerformed

    private void btnViewHCBudget1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHCBudget1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewHCBudget1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HealthViewGraphicallyBtn;
    private javax.swing.JButton btnViewHCBudget1;
    private javax.swing.JButton btnViewHCEvents;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
