/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GoGreenAdminWorkArea;

import Business.BudgetData.Budget;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.GoGreenEnterprise;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saurabhkulkarni
 */
public class AnalyzeBudgetJpanel extends javax.swing.JPanel {

    /**
     * Creates new form AnalyzeBudgetJpanel
     */
   
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private GoGreenEnterprise goGreenEnterprise;
    AnalyzeBudgetJpanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        this.goGreenEnterprise = (GoGreenEnterprise)enterprise;
        populateBudgetTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBudget = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        manageBudgetBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMessageArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        tblBudget.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Budget Alloted", "Organization Name", "Budget Year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBudget.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblBudget);
        tblBudget.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        manageBudgetBtn.setBackground(new java.awt.Color(255, 255, 255));
        manageBudgetBtn.setText("Manage Budget");
        manageBudgetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBudgetBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Message from Budget Manager: ");

        txtMessageArea.setEditable(false);
        txtMessageArea.setColumns(20);
        txtMessageArea.setRows(5);
        jScrollPane2.setViewportView(txtMessageArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manageBudgetBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane2)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageBudgetBtn)
                    .addComponent(backBtn))
                .addContainerGap(166, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backBtnActionPerformed

    private void manageBudgetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBudgetBtnActionPerformed
        // TODO add your handling code here:
        ManageBudgetJpanel manageBudgetJpanel = new ManageBudgetJpanel(userProcessContainer,userAccount,goGreenEnterprise,business);
        userProcessContainer.add("Analyze Budget work area", manageBudgetJpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
                
    }//GEN-LAST:event_manageBudgetBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton manageBudgetBtn;
    private javax.swing.JTable tblBudget;
    private javax.swing.JTextArea txtMessageArea;
    // End of variables declaration//GEN-END:variables

    private void populateBudgetTable() {
        
        DefaultTableModel model = (DefaultTableModel)tblBudget.getModel();
        
        model.setRowCount(0);
        if(null !=goGreenEnterprise.getWorkQueue().getWorkRequestlist() ){
            
                
            for(WorkRequest request : goGreenEnterprise.getWorkQueue().getWorkRequestlist()){
                txtMessageArea.setText(request.getMessage());
                System.out.println("Rec: "+request.getReceiver());
                System.out.println("Role: "+Role.RoleType.GreenAdmin.toString());
                
                if(request.getReceiver().equals(Role.RoleType.GreenAdmin)){
                    System.out.println("ABC:"+request.getMessage());
                    for(Budget budget : request.getBudgetList()){
                    System.out.println("ABC:"+budget.getOrgBudget());
                    Object[] row = new Object[3];
                    row[0] = budget.getOrgBudget();
                    row[1] = budget.getOrgName();
                    row[2] = budget.getBudgetYear();
                    model.addRow(row);
                    }
                    
                }
            
            }
        }
    }
    
}
