/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GoGreenAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author saurabhkulkarni
 */
public class GreenManagerAdminJpanel extends javax.swing.JPanel {

    /**
     * Creates new form GreenManageAdminJpanel
     */

    JPanel userProcessContainer;
    EcoSystem business;
    UserAccount userAccount;
    Enterprise enterprise;
    public GreenManagerAdminJpanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        analyzeBudgetBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        analyzeBudgetBtn.setBackground(new java.awt.Color(255, 255, 255));
        analyzeBudgetBtn.setText("Analyze Budget");
        analyzeBudgetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyzeBudgetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(analyzeBudgetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(analyzeBudgetBtn)
                .addContainerGap(396, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void analyzeBudgetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzeBudgetBtnActionPerformed
        // TODO add your handling code here:
        AnalyzeBudgetJpanel analyzeBudgetJpanel = new AnalyzeBudgetJpanel(userProcessContainer, userAccount, enterprise, business);
        userProcessContainer.add("Analyze Budget work area", analyzeBudgetJpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_analyzeBudgetBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analyzeBudgetBtn;
    // End of variables declaration//GEN-END:variables
}
